/* Turns icons/jar/*.png into js/art/jar-images.js, so the candy jar pictures survive the
 * single-file build and work offline. Usage: node scripts/embed-jar.js */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const dir = path.join(root, 'icons/jar');
const files = fs.readdirSync(dir).filter((f) => f.endsWith('.png')).sort();
const jarEntries = [], candyEntries = [];
files.forEach((f) => {
  const key = path.basename(f, '.png');
  const b64 = fs.readFileSync(path.join(dir, f)).toString('base64');
  const uri = `data:image/png;base64,${b64}`;
  const m = key.match(/^jar-(\d+)$/);
  if (m) { jarEntries[Number(m[1])] = uri; return; }
  const c = key.match(/^candy-(\d+)$/);
  if (c) { candyEntries[Number(c[1])] = uri; return; }
});
const body = `/* Generated by scripts/embed-jar.js from icons/jar/ — do not edit by hand.\n`
  + ` * The candy jar picture Harper's parent chose, one image per fill level (0 to 9), plus the\n`
  + ` * individual candy pictures. HL.candyJar()/HL.candy() use these when present and fall back to\n`
  + ` * the drawn SVG jar when they are not. */\n`
  + `window.HL = window.HL || {};\n`
  + `window.HL.jarImages = [\n${jarEntries.map((u) => `  '${u}',`).join('\n')}\n];\n`
  + `window.HL.candyImages = [\n${candyEntries.map((u) => `  '${u}',`).join('\n')}\n];\n`;
fs.writeFileSync(path.join(root, 'js/art/jar-images.js'), body);
console.log(`${jarEntries.length} jar states + ${candyEntries.length} candies -> js/art/jar-images.js (${(body.length / 1024).toFixed(0)} KB)`);
