/* Turns icons/animals/*.png into js/art/animal-images.js, so the pictures survive the
 * single-file build and work offline. Usage: node scripts/embed-animals.js */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const dir = path.join(root, 'icons/animals');
const files = fs.readdirSync(dir).filter((f) => f.endsWith('.png')).sort();
const entries = files.map((f) => {
  const key = path.basename(f, '.png');
  const b64 = fs.readFileSync(path.join(dir, f)).toString('base64');
  return `  ${key}: '${`data:image/png;base64,${b64}`}',`;
});
const body = `/* Generated by scripts/embed-animals.js from icons/animals/ — do not edit by hand.\n`
  + ` * Harper's own animal pictures, keyed by mascot name. HL.animal() uses one of these when it\n`
  + ` * exists and falls back to the drawn SVG when it does not. */\n`
  + `window.HL = window.HL || {};\nwindow.HL.animalImages = {\n${entries.join('\n')}\n};\n`;
fs.writeFileSync(path.join(root, 'js/art/animal-images.js'), body);
console.log(`${files.length} pictures -> js/art/animal-images.js (${(body.length / 1024).toFixed(0)} KB)`);
