/* Turns an image in icons/ into a JS file holding a data URI, so it survives the single-file
 * build (which inlines JS but does not rewrite image URLs) and works offline with no extra
 * request. Usage: node scripts/embed-image.js icons/piggy.png js/art/piggy-image.js HL.piggyImage */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const [src, out, name] = process.argv.slice(2);
if (!src || !out || !name) { console.error('usage: embed-image.js <src> <out.js> <HL.prop>'); process.exit(1); }
const buf = fs.readFileSync(path.join(root, src));
const type = { '.png': 'image/png', '.webp': 'image/webp', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml' }[path.extname(src).toLowerCase()];
if (!type) { console.error('unsupported image type: ' + src); process.exit(1); }
const prop = name.replace(/^HL\./, '');
const body = `/* Generated by scripts/embed-image.js from ${src} — do not edit by hand. */\nwindow.HL = window.HL || {};\nwindow.HL.${prop} = '${`data:${type};base64,${buf.toString('base64')}`}';\n`;
fs.writeFileSync(path.join(root, out), body);
console.log(`${src} (${(buf.length / 1024).toFixed(1)} KB) -> ${out} (${(body.length / 1024).toFixed(1)} KB)`);
